spring:
  batch:
    job:
      enabled: true
      name: ${job.name:NONE}


jquants:
  email: dkstjsgh5@gmail.com
  password: aA58450002024

slack:
  key: https://hooks.slack.com/services/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
