spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pAN9nWJV
    url: 'jdbc:mysql://localhost:3306/stock_automation'
  sql:
    init:
      mode: never