name: 株価データ照会

on:
  schedule:
    - cron: '0 16 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: build with Gradle
        run: ./gradlew clean :build -x test
      - name: Run batcgh　
        run: java -jar -Dspring.batch.job.name=stockSlackJob -Dspring.profiles.active=github ./build/libs/stockAutomation-0.0.1-SNAPSHOT.jar stock=9449
